# Generated by Django 4.1.7 on 2023-03-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
